name: ssk_manager
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  auto_size_text: 3.0.0
  cached_network_image: 3.2.1
  flutter_animate: 1.0.0
  flutter_cache_manager: 3.3.0
  font_awesome_flutter: 10.1.0
  from_css_color: 2.0.0
  google_fonts: 3.0.1
  intl: 0.17.0
  json_path: 0.4.1
  page_transition: 2.0.4
  provider: 6.0.4
  shared_preferences: 2.0.15
  timeago: 3.2.2
  url_launcher: 6.1.5
  sqflite: ^2.2.6
  sqflite_common_ffi: ^2.2.2
  data_table_2: ^2.4.1
  table_calendar: ^3.0.8
  syncfusion_flutter_pdf: ^20.4.54
  open_filex: ^4.3.2
  path_provider: ^2.0.14
  dropdown_button2: ^2.0.0
  syncfusion_flutter_sliders: ^20.4.54
  graphic: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

# assets:
#   - assets/dataset.json